import OpenAI from "openai";

export default defineEventHandler(async () => {
  const config = useRuntimeConfig();
  const openai = new OpenAI({
    apiKey: config.openaiApiKey,
  });

  const response = await openai.chat.completions.create({
    model: "gpt-4o-mini",
    store: true,
    response_format: { type: "json_object" },
    messages: [
      {
        role: "user",
        content: `Generate ${getRandomType()?.toLowerCase()} English sentence about ${getRandomTopic()?.toLowerCase()} with Japanese translation in a JSON format like { sentence: "...", translation: "..." }`,
      },
    ],
  });

  return JSON.parse(response.choices[0]?.message.content || "{}");
});

const topics = [
  "Weather",
  "Travel",
  "Food",
  "Hobbies",
  "Sports",
  "Music",
  "Movies",
  "Books",
  "Friendship",
  "Love",
  "School",
  "Work",
  "Technology",
  "Social media",
  "Shopping",
  "Family",
  "Health",
  "Exercise",
  "Nature",
  "Animals",
  "Holidays",
  "Seasons",
  "Transportation",
  "Dreams",
  "Goals",
  "Emotions",
  "Time",
  "Money",
  "History",
  "Art",
  "Photography",
  "Language learning",
  "Culture",
  "Traditions",
  "Festivals",
  "Cooking",
  "Fashion",
  "Beauty",
  "Home",
  "Cleaning",
  "Gardening",
  "Science",
  "Space",
  "Environment",
  "Pollution",
  "Inventions",
  "News",
  "Politics",
  "Economy",
  "Internet",
  "Gaming",
  "Pets",
  "Relationships",
  "Childhood",
  "Memories",
  "Future",
  "Past",
  "Success",
  "Failure",
  "Adventure",
  "Mystery",
  "Happiness",
  "Sadness",
  "Kindness",
  "Helping others",
  "Learning",
  "Teaching",
  "Volunteering",
  "Languages",
  "Jobs",
  "Careers",
  "Motivation",
  "Productivity",
  "Sleep",
  "Dream jobs",
  "Morning routine",
  "Night routine",
  "Hygiene",
  "Transportation problems",
  "City life",
  "Countryside",
  "Beach",
  "Mountains",
  "Rain",
  "Snow",
  "Sunshine",
  "Technology in education",
  "Smartphones",
  "Virtual reality",
  "Artificial intelligence",
  "Robots",
  "Books vs movies",
  "Online shopping",
  "Digital art",
  "Handwriting",
  "Public speaking",
  "Leadership",
  "Teamwork",
  "Conflict resolution",
  "Self-improvement",
  "Mindfulness",
  "Mental health",
  "Habits",
  "Celebrations",
];

const getRandomTopic = () => {
  return topics[Math.floor(Math.random() * topics.length)];
};

const types = [
  "Polite",
  "Casual",
  "Formal",
  "Simple",
  "Complex",
  "Question",
  "Negative",
  "Imperative",
  "Exclamatory",
  "Conditional",
];

const getRandomType = () => {
  return types[Math.floor(Math.random() * types.length)];
};
